import NavBar from "@/components/NavBar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body className="max-w-screen-xl mx-auto p-5">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
